lab3
DcDrugs/Calendar pull request #2
Opened 2022-04-17 20:39 UTC by DcDrugs

create lab3

2022-04-22 08:42 UTC, Nastik1811 requested changes
Ваша вёрстка не соответствует тому, что было на макете. Кроме того, я не вижу формы для создания новой задачи

2022-04-30 17:13 UTC, DcDrugs commented
Я немного отошел от идеала макета в угоду красоты.

2022-05-02 16:55 UTC, Nastik1811 commented
> Я немного отошел от идеала макета в угоду красоты. Форма для создания новой задачи появляется только по нажатию кнопки(для этого нужен js (в html класс "popup") ![image](https://user-images.githubusercontent.com/56217484/166117417-b9c47f79-2d0b-47e3-8d39-280f27dba9e3.png)

Ну я больше про теги, которые мы обсуждали на предыдущем этапе
<img width="300" alt="image" src="https://user-images.githubusercontent.com/37243282/166290816-989b5c67-8ef5-4493-8134-443dd205582d.png">

2022-05-02 16:55 UTC, Nastik1811 commented
вот эти
<img width="298" alt="image" src="https://user-images.githubusercontent.com/37243282/166290911-c0a2da2a-9eb1-46b2-a04c-85de853538d2.png">

2022-05-03 11:04 UTC, DcDrugs commented
> вот эти, например <img alt="image" width="298" src="https://user-images.githubusercontent.com/37243282/166290911-c0a2da2a-9eb1-46b2-a04c-85de853538d2.png">

Я еще не особо знаком, как js будет работать с html. Пока сделал только шаблон. В любом случае, я еще буду менять это на этапе js.

2022-05-04 10:52 UTC, Nastik1811 commented
Вёрстка и стили на следующих этапах меняться не должны существенно. В этом и смысл дробления проекта на этапы

2022-05-10 14:37 UTC, Nastik1811 requested changes

2022-05-10 14:37 UTC, Nastik1811 commented on index.html
> +                    <button class="accordion">Встретиться с друзьями</button>
а почему это кнопка?

2022-05-10 14:37 UTC, Nastik1811 commented on index.html
> +                <p></p>
это что?

2022-05-10 14:37 UTC, Nastik1811 commented on style/style.css
> +}
это как?

2022-05-10 14:37 UTC, Nastik1811 commented on style/style.css
> +        height: 100vh;
сделайте без 100vh

2022-05-10 14:37 UTC, Nastik1811 commented on style/popup-style.css
> +    outline: none !important;
зачем вам important здесь?

2022-05-10 14:37 UTC, Nastik1811 commented on style/popup-style.css
> +    outline: none !important;
и нельзя просто убрать  focus и не добавить свои стили

2022-05-10 14:37 UTC, Nastik1811 commented on style/popup-style.css
> +    float: right;
в задании написано не использовать float

2022-05-10 14:37 UTC, Nastik1811 commented on style/date-style.css
> +    width: calc(40.2rem/7);
а тут откуда цифры взялись?

2022-05-10 20:08 UTC, DcDrugs commented on index.html
> +                    <button class="accordion">Встретиться с друзьями</button>
> а почему это кнопка?

![image](https://user-images.githubusercontent.com/56217484/167713138-1cc8ab61-6059-4e4a-a79c-ef9dddda3854.png)
JS разворачивает и выводит информацию.

2022-05-10 20:14 UTC, DcDrugs commented on index.html
> +                <p></p>
Костыль, тк Я прописывал для time-manager margin-top и ничего не происходило

![image](https://user-images.githubusercontent.com/56217484/167714100-394f8296-a1fc-45e2-81b3-29978ef818d6.png)

2022-05-10 20:17 UTC, DcDrugs commented on style/style.css
> +}
c: 
![image](https://user-images.githubusercontent.com/56217484/167714505-eda811c5-2072-46fe-a2cc-3fc442221d06.png)

без:
![image](https://user-images.githubusercontent.com/56217484/167714664-3ea8a624-0436-493d-b5dc-70adef3680fa.png)

2022-05-10 20:20 UTC, DcDrugs commented on style/style.css
> +        height: 100vh;
Исправлю, спасибо

2022-05-10 20:24 UTC, DcDrugs commented on style/popup-style.css
> +    outline: none !important;
Это проект - полигон, я просто баловался со всем, что нашел, и возможно, что-то забыл убрать. Уберу, спасибо

2022-05-10 20:51 UTC, DcDrugs commented on style/date-style.css
> +    width: calc(40.2rem/7);
Подгонял под то, как я его вижу, не использовал %, потому что мне не нравиться, как оно искажает мой календарь.

2022-05-10 21:02 UTC, DcDrugs commented on style/popup-style.css
> +    float: right;
![image](https://user-images.githubusercontent.com/56217484/167721210-dffd512a-cdc0-419e-91a6-de045f4ec498.png)

Возможно, я где-то не посмотрел, но к сожалению не нашел, но исправлю, спасибо

2022-05-13 04:08 UTC, DcDrugs commented
Мне бы просто сдать все лаб. работы. Не важно на какую оценку

2022-05-14 10:28 UTC, Nastik1811 approved these changes

2022-05-14 18:32 UTC, merged